### PR TITLE
vegan :)

### PR DESCRIPTION
**Pull request by shawna-slh**
I'm not vegan myself, yet do not want to potentially offend or even bother those who are -- especially when it doesn't matter at all for the purpose of the video what the food is. I don't care whether it's peanut butter or other, but let's make it vegan.

/me bases this on @yatil 's survey comment: "[Although I would prefer Peanut butter instead of eggs on toast or something like that.]"

### CODE REVIEW

**Comment by yatil** [comment]
\o/

**Comment by iadawn** [comment]
But I have a nut allergy ;-)

**Comment by yatil** [comment]
> But I have a nut allergy ;-)

I do, too, but this change isn’t about us ;-p

**Comment by iadawn** [comment]
Actually I don't... I was being fascicious ;-)

**Comment by yatil** [comment]
Well, now you know my GREATEST WEAKNESS!! ;-)

**Pull request merged**
