### PR TITLE
title to match h1

### PR DESCRIPTION
**Pull request by shawna-slh**

### CODE REVIEW

**Comment by nitedog** [comment]
AFAIK this was added for SEO. Happy to remove but should probably notify EOWG.

@vuxcaleb any thoughts on this, I think this may have been added by you?

**Comment by vuxcaleb** [comment]
@slhenry it would be ideal to not make the title's match the current h1's both for SEO and also Usability. When people search in Google we want to make it easy for them to find the specific Perspective content, and so front-loading the title with the relevant keywords will allow people to read less before finding and clicking on the search result.

So for example let's look at Keyboard Compatibility as an example:

When we front-load the relevant keywords we get a Google SERP that is easier and faster to parse.
serp-keyboard-front-loading-title
Search Result Preview: [https://slerpee.com/edit/mlnnarYTmnfUx8pjxL08Cg]

But when we make the title the same as the h1 the Google SERP is harder to parse:
serp-keyboard-title-same-as-h1
Search Result Preview: [https://slerpee.com/edit/mYywOWGDNUYA927dmymCAw]

If you want them to match it would be ideal to change all the h1's to match the title's using the following format:

`Keyboard Compatibility - Web Accessibility Perspectives Videos`

`<Perspective Title> - Web Accessibility Perspectives Videos`

**Comment by vuxcaleb** [comment]
@slhenry @nitedog the exception would be the overview page where it makes sense to make the format front-loaded with the Resource name:

`Web Accessibility Perspectives: Explore the Impact and Benefits for Everyone`

**Comment by yatil** [comment]
I tend to vote leave as is, but I don’t have strong feelings either way. (I just noticed that it is not clear what the resource is when you’re not explicitly mentioning “videos”.)

**Comment by vuxcaleb** [comment]
@yatil I agree - using the word "videos" does make it more clear.

**Comment by shawna-slh** [comment]
I thought it was a simple QA error that the title didn't match the h1 on the overview page. :-)

Please make sure that we are putting ACCESSIBILITY (including "usable accessibility") as a higher priority than SEO -- in determining the best page titles and other things.

With that as the deciding factor, I'm OK with whatever y'all decide is best.

**Comment by nitedog** [comment]
@slhenry what is the specific accessibility concern here?

**Pull request closed without merging**
