### PR TITLE
[understandable] Consistent link naming

### PR DESCRIPTION
**Pull request by susanatx**
Changed mobile link from "understandable" to more specific title.

### CODE REVIEW

**Comment by nitedog** [comment]
But that is the title of only one of the sub-items of the "Understandable" section, and mismatches the link target.

**Comment by susanatx** [comment]
I see your point but still feel the link text should be more clear. I need to think a little more about a possible solution.

**Comment by nitedog** [comment]
@susanatx how do you feel about referencing each item in that section individually:
- Long words, long and complex sentences, jargon
- Content spawning new windows without warning user
- Blinking, moving, scrolling or auto-updating content

**Comment by susanatx** [comment]
@nitedog I think that's a great idea content-wise. It definitely gives the user more context for what they're clicking through. Thanks for the quick solution. My brain is moving slowly today.

**Comment by bakkenb** [comment]
+1

**Comment by nitedog** [comment]
Edited accordingly.

**Pull request closed without merging**
